import { defineConfig, presetWind, presetIcons } from 'unocss';

export default defineConfig({
  presets: [
    presetWind(),
    presetIcons({
      scale: 1.2,
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  theme: {
    colors: {
      // Must match design-tokens.css `--nr-*` values one-for-one — Uno
      // generates classes like `bg-nr-red` at build time using these
      // literals, so any drift here means a different rendered red
      // than the CSS-variable version. Brand red is #DA0000.
      nr: {
        // ── Static brand / docs colours ─────────────────────────────────
        // These are literal hex values used in always-dark contexts (docs
        // footer, code blocks) or where the value never changes with theme.
        // UnoCSS generates `bg-nr-red`, `text-nr-bg-dark` etc. at build time.
        red: '#DA0000',
        'red-hover': '#B30000',
        // #9F0000 = AA-accessible dark red (5.9:1 on white). Matches
        // --nr-red-dark and --nr-text-link in design-tokens.css and
        // --sl-color-accent-high in starlight-custom.css.
        'red-dark': '#9F0000',
        'red-light': '#FCE5E5',
        'red-subtle': 'rgba(218, 0, 0, 0.06)',
        black: '#1A1A1A',
        'bg-dark': '#1E1E1E',
        'bg-darker': '#161616',
        'bg-light': '#f5f5f5',
        'bg-content': '#fff',
        text: '#2D2D2D',
        'text-secondary': '#8A8A8A',
        'text-light': '#f0f0f0',
        link: '#DA0000',
        'code-text': '#D4394B',
        'code-bg': '#FFF5F5',
        'border-light': '#F0F0F0',

        // ── Theme-aware surface & text tokens (CSS-variable backed) ──────
        // Values are CSS variable references. UnoCSS emits e.g.
        // `background-color: var(--nr-surface)` — the variable resolves to
        // the correct light or dark value at runtime via design-tokens.css.
        // Opacity modifiers (/20 etc.) do NOT work on var()-backed colours.
        surface: 'var(--nr-surface)',
        'surface-alt': 'var(--nr-surface-alt)',
        'surface-elevated': 'var(--nr-surface-elevated)',
        'text-strong': 'var(--nr-text-strong)',
        'text-body': 'var(--nr-text-body)',
        'text-muted': 'var(--nr-text-muted)',
        'text-faint': 'var(--nr-text-faint)',
        border: 'var(--nr-border)',
        'border-strong': 'var(--nr-border-strong)',
      },
    },
    // The same two variables --font-sans and --font-mono point at in
    // design-tokens.css, generated by the `fonts` block in astro.config.mjs
    // (Astro's Fonts API) and emitted on :root by <Font /> in the head. Uno
    // drops these values into `font-family` verbatim, so a family list here
    // would be a second copy of the chain that drifts from the tokens.
    //
    // Naming the families literally is not an option either, and that is the
    // real reason these are variables rather than 'Google Sans Flex': the
    // generated @font-face rules append a hash of the family config to the
    // family name, so a literal 'Google Sans Flex' matches no face and falls
    // through to a system font without any error. `font-sans` the utility and
    // var(--font-sans) the token now resolve to one face with one fallback
    // chain, including the metric-matched fallbacks Astro generates.
    fontFamily: {
      sans: 'var(--font-google-sans-flex)',
      heading: 'var(--font-google-sans-flex)',
      mono: 'var(--font-ubuntu-mono)',
    },
    breakpoints: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1200px',
      '2xl': '1440px',
    },
    // Override Tailwind's default spacing scale to match the design system
    // --space-1..10 tokens: 4/8/12/16/24/32/48/64/96/128 px.
    // Tailwind's defaults match at 1–4 but diverge at 5+ (5=20px vs 24px).
    // Overriding keeps utility classes like `gap-5` = 24px = `--space-5`.
    spacing: {
      '0': '0px',
      px: '1px',
      '0.5': '2px',
      '1': '4px',
      '1.5': '6px',
      '2': '8px',
      '2.5': '10px',
      '3': '12px',
      '3.5': '14px',
      '4': '16px',
      '5': '24px',
      '6': '32px',
      '7': '48px',
      '8': '64px',
      '9': '96px',
      '10': '128px',
      '11': '44px',
      '12': '48px',
      '14': '56px',
      '16': '64px',
      '20': '80px',
      '24': '96px',
      '28': '112px',
      '32': '128px',
      '36': '144px',
      '40': '160px',
      '44': '176px',
      '48': '192px',
      '52': '208px',
      '56': '224px',
      '60': '240px',
      '64': '256px',
      '72': '288px',
      '80': '320px',
      '96': '384px',
    },
  },
  shortcuts: {
    // Docs breadcrumb bar (Starlight layout)
    'nr-breadcrumbs': 'bg-nr-red min-h-[50px] flex items-center',
    'nr-breadcrumbs-inner':
      'max-w-[1200px] mx-auto px-5 w-full text-white font-heading text-[16px] flex list-none',
    'nr-breadcrumbs-link': 'text-white no-underline hover:underline hover:text-white',
    // Docs section heading red underline (pb-3 = 12px = --space-3)
    'nr-section-heading': 'border-b-3 border-nr-red pb-3',
    // Marketing page h1 underline (pb-4 = 16px = --space-4; used on blog/about page headings)
    'nr-page-heading': 'border-b-3 border-nr-red pb-4 mb-6 tracking-[-0.025em] text-nr-text-strong',
  },
});
